repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      args: [
        --args=--deep,
        # --args=--module, # TODO enable it after ensuring `terraform init`
        # --args=--enable-rule=terraform_comment_syntax,
        # --args=--enable-rule=terraform_deprecated_index,
        # --args=--enable-rule=terraform_documented_outputs,
        # --args=--enable-rule=terraform_documented_variables,
        # --args=--enable-rule=terraform_required_providers,
        # --args=--enable-rule=terraform_typed_variables,
        --args=--enable-rule=terraform_naming_convention,
        # --args=--enable-rule=terraform_required_version,
        # --args=--enable-rule=terraform_unused_declarations,
      ]
    - id: terraform_tfsec
      args: [ '--args=-e GCP003,GCP004' ]
      # GCP002 Unencrypted bucket.
      #   Ignore for transitional period. TODO enable it after encrypting all buckets.
      # GCP003 An inbound vpc rule allows traffic from /0.
      #   Ignore it because we rarely use traditional rules for security. Instead we do it with our own firewalls-as-VMs.
      # GCP004 An outbound vpc rule allows traffic from /0.
      #   Ignore it because we rarely use traditional rules for security. Instead we do it with our own firewalls-as-VMs.
