repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      args: [
        --args=--module,
        --args=--deep,
        # disabled ##############################################
        --args=--disable-rule=terraform_comment_syntax,
        --args=--disable-rule=terraform_documented_outputs,
        --args=--disable-rule=terraform_documented_variables,
        --args=--disable-rule=terraform_required_providers,
        --args=--disable-rule=terraform_typed_variables,
        # enabled ###############################################
        --args=--enable-rule=terraform_deprecated_index,
        --args=--enable-rule=terraform_naming_convention,
        --args=--enable-rule=terraform_required_version,
        --args=--enable-rule=terraform_unused_declarations,
      ]
    - id: terraform_tfsec
      args: [
        --args=-e GCP003,GCP004
      ]
