
---
name: CI/CD
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: terraform validate
        run: |
          mkdir -p ~/.ssh
          echo dummy file required for terraform validate to pass >> ~/.ssh/id_rsa
          cd "$GITHUB_WORKSPACE"
          for dir in $(find modules examples -type d -not \( -name ".?*" -o -name regional_workspaces \) -maxdepth 1 -mindepth 1 );
          do
            echo "Processing directory: $dir"
            cd "$GITHUB_WORKSPACE/$dir"
            terraform init -backend=false
            terraform validate
          done

      - name: Run the Pre-Commit Framework Action
        uses: ./.github/action-precommit

  release:
    name: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [validate]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release and publish
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.2
          extra_plugins: |
            conventional-changelog-conventionalcommits@^4.5.0
            @semantic-release/git@^9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
