name: main

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-tflint@master
      with:
        github_token: ${{ secrets.github_token }}

  pre-commit:
    runs-on: ubuntu-latest
    # container: node:10.16-jessie
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: |
        curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")" > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
        curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
        echo "PATH=$PATH"
        go mod init dummy # because cannot use path@version syntax in GOPATH mode
        export GO111MODULE=on
        go get -u github.com/tfsec/tfsec/cmd/tfsec@v0.30.1
        sudo mv /home/runner/go/bin/tfsec /usr/local/bin/tfsec
    - uses: pre-commit/action@v2.0.0
