name: main

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PaloAltoNetworks/terraform-google-vmseries-modules@gh_actions
  pre-commit:
    runs-on: ubuntu-latest
    # container: node:10.16-jessie
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: |
        curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")" > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
        curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
        curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?tfsec-linux-amd64")" > tfsec && chmod +x tfsec && sudo mv tfsec /usr/local/bin/
    - uses: pre-commit/action@v2.0.0
