name: PR CI
run-name: "CI pipeline for PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

permissions:
  contents: read
  actions: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: ['main']

jobs:
  pr_ci_wrkflw:
    name: Run CI
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/pr_ci.yml@gcp-makefile-with-terratest
    if: github.actor != 'dependabot[bot]'
    secrets: inherit
    with:
      cloud: gcp
      tf_version: 1.2 1.3 1.4 1.5
      validate_max_parallel: 20
      test_max_parallel: 10
      fail_fast: false
      terratest_action: Plan # keep in mind that this has to start with capital letter